### ISSUE TITLE
Utilize labels only style

### ISSUE THREAD

**Issue by anniinakovalainen** [GispoCoding/tarmo#124] opened 2022-03-17 11:13 UTC
Utilize labels only style which is found in map-styles folder.

**Comment by SannaJokela** [comment] 2022-04-14 12:26
@mvaaltola do you know what this issue means?

**Comment by SannaJokela** [comment] 2022-04-19 08:00
This issue is related to background map: labels are now detached from the rest of the background, so theys should be brought on top of other features if possible.

**Comment by mvaaltola** [comment] 2022-04-19 08:06
Duplicate of #31

**Closed by mvaaltola** 2022-04-19 08:06 UTC
Labels: mapstyling
