### ISSUE TITLE
Start view extent to Tampere city region

### ISSUE THREAD

**Issue by SannaJokela** [GispoCoding/tarmo#143] opened 2022-03-24 12:06 UTC
Start view should be at some suitable extent that only Tampere city region can be visible.

**Comment by pavetsu14** [comment] 2022-03-30 08:46
Duplicate of issue #29 ?

**Comment by SannaJokela** [comment] 2022-03-30 09:07
@pavetsu14 no they are two different things: the start extent (this issue) and masking the data (issue #29)

**Closed** 2022-05-02 14:08 UTC
Labels: frontend
